---
- hosts: all
  tasks:
    - name: install README.md.oob-mgmt-server
      copy:
        src: README.md.oob-mgmt-server
        dest: /home/vagrant/README.md


    - name: git clone kargo
      git:
        repo: "https://github.com/linuxsimba/kargo"
        version: 1s2l3s-setup
        dest: /home/vagrant/kargo
    - name: git clone kubernetes l3-clos repo
      git:
        repo: "https://github.com/linuxsimba/kubernetes-cumulus-l3-clos"
        version: weave
        dest: /home/vagrant/k8s-l3-clos

    - name: create ssh key
      user: name=vagrant generate_ssh_key=yes

    - name: copy kargo ssh keys
      copy:
        src: "./{{item}}"
        dest: "/home/vagrant/.ssh/{{item}}"
        mode: 0400
      with_items:
        - kargo-test.priv
        - kargo-test.pub
      register: copied_keys

    - name: reboot the server
      shell: sleep 2 && shutdown -r now "Ansible updates triggered"
      poll: 0
      async: 1
      become: true

- hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: wait for oob-mgmt-server to come back online
      wait_for:
        port: 22
        host: "{{ ansible_ssh_host }}"
        delay: 10
      when: copied_keys.changed == True

    - name: check if oob-mgmt switch is installed
      shell: "vagrant status | grep oob-mgmt-switch | grep running"
      register: mgmt_switch_installed
      failed_when: "mgmt_switch_installed.rc > 100"
      changed_when: false

    - name: start up oob mgmt switch
      command: vagrant up oob-mgmt-switch
      when: mgmt_switch_installed.rc == 1

    - name: check if all the VMs are up
      shell: vagrant status | awk '/running/'  | wc -l
      register: num_of_running_vms
      failed_when: "num_of_running_vms.rc > 100"
      changed_when: false

    # Ansible int filter not working as expected  Issues #4170
    - name: startup the remaining VMs
      command: vagrant up k8s1 k8s2 k8s3 leaf1 leaf2 spine1
      when: num_of_running_vms.stdout != "8"

- hosts: all
  tasks:
    - pause: seconds=8

    - name: check that server and switch VMs have come back up
      shell: ansible -m ping all
      args:
        chdir: /home/vagrant/k8s-l3-clos
      register: task_result
      until: task_result.rc == 0
      retries: 6
      delay: 10
      changed_when: false

    # TODO: Check if playbook is installed on the switches..
    - name: install switch config
      shell: ansible-playbook playbooks/site.yml -l switches
      args:
        chdir: /home/vagrant/k8s-l3-clos

    - name: install host config
      shell: ansible-playbook playbooks/site.yml -l host
      args:
        chdir: /home/vagrant/k8s-l3-clos

    # TODO only do this if the playbook executed succesfully
    - name: reboot all k8s hosts
      shell: ansible -b -m shell -a "(sleep 5; reboot)&" host
      args:
        chdir: /home/vagrant/k8s-l3-clos

    - pause: seconds=8

    # only do this if the playbook was executed successfully
    - name: check that servers have come back up
      shell: ansible -m ping host
      args:
        chdir: /home/vagrant/k8s-l3-clos
      register: task_result
      until: task_result.rc == 0
      retries: 6
      delay: 10
      changed_when: false

    - name: copy inventory hosts from infra setup to kubernetes repo
      copy:
        src: /home/vagrant/k8s-l3-clos/inventory/hosts
        dest: /home/vagrant/kargo/inventory/hosts

    # check if kubernetes is installed
    - name: install k8s using kargo
      shell: ansible-playbook cluster.yml
      args:
        chdir: /home/vagrant/kargo


    - debug: msg="type vagrant ssh oob-mgmt-server. follow instructions in README.md on the server"
