---
- hosts: spine
  roles:
    - { role: l3-clos, tags: ['spine'] }

- hosts: leaf
  roles:
    - { role: tor, tags: ['leaf'] }

- hosts: host
  roles:
    - { role: host-l2-to-tor, tags: ['l2-to-tor'] }
