---
- host: spine
  roles:
    - { role: l3-clos, tags: ['l3-clos'] }

- hosts: leaf
  roles:
    - { role: tor, tags: ['l3-leaf-spine'] }

- hosts: host
  roles:
    - { role: regular-l2, tags: ['roh'] }
